# Generated by Django 5.2.4 on 2025-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='about',
            field=models.TextField(verbose_name='About Plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('herb', 'Herb')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='plants/', verbose_name='Plant Image'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False, verbose_name='Edible'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Plant Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='used_for',
            field=models.TextField(verbose_name='Uses'),
        ),
    ]
